import Foundation
import Testing
@testable import YakamozCore

@Suite("AgentVaultFactory")
struct AgentVaultFactoryTests {
    private func makeTempRoot() -> URL {
        FileManager.default.temporaryDirectory.appending(path: "AgentVaultFactoryTests-\(UUID().uuidString)")
    }

    @Test("vaultRoot is deterministic and per-agent-id namespaced")
    func vaultRootIsDeterministicAndNamespaced() {
        let base = makeTempRoot()
        let factory = AgentVaultFactory(baseDirectory: base)
        let idA = UUID()
        let idB = UUID()

        let rootA1 = factory.vaultRoot(for: idA)
        let rootA2 = factory.vaultRoot(for: idA)
        let rootB = factory.vaultRoot(for: idB)

        #expect(rootA1 == rootA2)
        #expect(rootA1 != rootB)
        #expect(rootA1.path == base.appending(path: "Agents/\(idA.uuidString)").path)
    }

    @Test("createVault produces NOTES.md, WORKFLOW.md, and Memory/INDEX.md")
    func createVaultProducesAllFiles() throws {
        let base = makeTempRoot()
        defer { try? FileManager.default.removeItem(at: base) }
        let factory = AgentVaultFactory(baseDirectory: base)
        let agent = AgentModel(name: "Ada", instructions: "Be precise.", vaultPath: "")

        let root = try factory.createVault(for: agent)

        let fm = FileManager.default
        #expect(fm.fileExists(atPath: root.appending(path: "NOTES.md").path))
        #expect(fm.fileExists(atPath: root.appending(path: "WORKFLOW.md").path))
        #expect(fm.fileExists(atPath: root.appending(path: "Memory/INDEX.md").path))

        let notes = try String(contentsOf: root.appending(path: "NOTES.md"), encoding: .utf8)
        #expect(notes.contains("standing facts"))

        let index = try String(contentsOf: root.appending(path: "Memory/INDEX.md"), encoding: .utf8)
        #expect(index.hasPrefix("# Memory Index"))

        let workflow = try String(contentsOf: root.appending(path: "WORKFLOW.md"), encoding: .utf8)
        #expect(workflow.contains("NOTES.md"))
        #expect(workflow.contains("Memory/"))
        #expect(workflow.contains("INDEX.md"))
        #expect(workflow.contains("Do not edit this file"))
    }

    @Test("createVault is idempotent: preserves NOTES.md and INDEX.md content, always rewrites WORKFLOW.md")
    func createVaultIsIdempotent() throws {
        let base = makeTempRoot()
        defer { try? FileManager.default.removeItem(at: base) }
        let factory = AgentVaultFactory(baseDirectory: base)
        let agent = AgentModel(name: "Ada", instructions: "Be precise.", vaultPath: "")

        let root = try factory.createVault(for: agent)

        let notesURL = root.appending(path: "NOTES.md")
        let indexURL = root.appending(path: "Memory/INDEX.md")
        let workflowURL = root.appending(path: "WORKFLOW.md")

        try "custom standing facts about Ada".write(to: notesURL, atomically: true, encoding: .utf8)
        try "# Memory Index\n- [[topic]] — a hook\n".write(to: indexURL, atomically: true, encoding: .utf8)
        try "stale content".write(to: workflowURL, atomically: true, encoding: .utf8)

        try factory.createVault(for: agent)

        let notes = try String(contentsOf: notesURL, encoding: .utf8)
        let index = try String(contentsOf: indexURL, encoding: .utf8)
        let workflow = try String(contentsOf: workflowURL, encoding: .utf8)

        #expect(notes == "custom standing facts about Ada")
        #expect(index == "# Memory Index\n- [[topic]] — a hook\n")
        #expect(workflow == AgentVaultFactory.workflowTemplate)
        #expect(workflow != "stale content")
    }

    @Test("regenerateWorkflowTemplate overwrites only WORKFLOW.md")
    func regenerateWorkflowTemplateOverwritesOnlyWorkflow() throws {
        let base = makeTempRoot()
        defer { try? FileManager.default.removeItem(at: base) }
        let factory = AgentVaultFactory(baseDirectory: base)
        let agent = AgentModel(name: "Ada", instructions: "Be precise.", vaultPath: "")

        let root = try factory.createVault(for: agent)
        let notesURL = root.appending(path: "NOTES.md")
        try "keep me".write(to: notesURL, atomically: true, encoding: .utf8)

        try factory.regenerateWorkflowTemplate(for: agent)

        let notes = try String(contentsOf: notesURL, encoding: .utf8)
        let workflow = try String(contentsOf: root.appending(path: "WORKFLOW.md"), encoding: .utf8)
        #expect(notes == "keep me")
        #expect(workflow == AgentVaultFactory.workflowTemplate)
    }

    @Test("deleteVault removes the vault tree")
    func deleteVaultRemovesTree() throws {
        let base = makeTempRoot()
        defer { try? FileManager.default.removeItem(at: base) }
        let factory = AgentVaultFactory(baseDirectory: base)
        let agent = AgentModel(name: "Ada", instructions: "Be precise.", vaultPath: "")

        let root = try factory.createVault(for: agent)
        #expect(FileManager.default.fileExists(atPath: root.path))

        try factory.deleteVault(for: agent.id)

        #expect(!FileManager.default.fileExists(atPath: root.path))
    }

    @Test("deleteVault on a missing vault is a no-op")
    func deleteVaultOnMissingVaultIsNoOp() throws {
        let base = makeTempRoot()
        defer { try? FileManager.default.removeItem(at: base) }
        let factory = AgentVaultFactory(baseDirectory: base)

        try factory.deleteVault(for: UUID())
    }
}
